{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":20,"msg":"Sync server version: 1.3.8 2022-02-25 10:58:11 -0600 50659ecda06a8b79a41f24c1fdff05187324402b","time":"2024-11-05T18:56:09.360Z","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"msg":"Acquiring actors for session 1730832969: ACTOR1","time":"2024-11-05T18:56:09.365Z","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"msg":"Session 1730832969 with label \"oneApp-login 7\" started at 2024-11-05 18:56:09 UTC","time":"2024-11-05T18:56:09.370Z","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.788264Z","msg":"Actor 29586 of type ACTOR1 was acquired by test session 1730832969","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":20,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8251842Z","msg":"DEBUG: Test actor JAR versions:","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":20,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8291328Z","msg":"DEBUG:   opentest-appium-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":20,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8311285Z","msg":"DEBUG:   opentest-base-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":20,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8482775Z","msg":"DEBUG:   opentest-selenium-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":40,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8556231Z","msg":"WARN: Failed to log extension JARs","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":10,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.8576034Z","msg":"TRACE: Firing SESSION_STARTED event...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.9408778Z","msg":"Including script file \"common-scripts\\csvTools.js\"...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.9570639Z","msg":"Including script file \"..\\..\\data\\config.yaml\"...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":50,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:12.9700527Z","msg":"ERROR: java.lang.RuntimeException: Failed to evaluate the \"dataSet\" property of the data-driven test as a JavaScript expression. The expression we evaluated was >>> (function() {\n  $include(\"common-scripts/csvTools.js\")\n  var urlData = $include(\"../../data/config.yaml\")\n  var loginData = $csvToJson(\"../../data/py-data/login-mail/login-mail.csv\")\n  return {\n    url: urlData,\n    data: loginData\n  }\n})()\n <<<.\r\n\tat org.getopentest.base.TestActor.evalDataSet(TestActor.java:1274)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:2975)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:3113)\r\n\tat org.getopentest.Main.main(Main.java:20)\r\nCaused by: java.lang.RuntimeException: Failed to run script file ..\\..\\data\\config.yaml\r\n\tat org.getopentest.base.TestActor.includeScriptFile(TestActor.java:2601)\r\n\tat org.getopentest.base.TestActor.lambda$evalIncludes$6(TestActor.java:1343)\r\n\tat java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)\r\n\tat org.getopentest.base.TestActor.evalIncludes(TestActor.java:1342)\r\n\tat org.getopentest.base.TestActor.access$600(TestActor.java:84)\r\n\tat org.getopentest.base.TestActor$15.accept(TestActor.java:629)\r\n\tat jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$163$1$\\^eval\\_/0x00000001003d4040.L:1(<eval>:3)\r\n\tat jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$162$\\^eval\\_/0x00000001003d3c40.:program(<eval>:1)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)\r\n\tat java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)\r\n\tat org.getopentest.base.TestActor.evalDataSet(TestActor.java:1272)\r\n\t... 3 more\r\nCaused by: javax.script.ScriptException: <eval>:5:2 Duplicate Label \"url\"\r\n  url: https://oneapp-STG-py.tigocloud.net/ingresar\r\n  ^ in <eval> at line number 5 at column number 2\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:544)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)\r\n\tat java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)\r\n\tat org.getopentest.base.TestActor.includeScriptFile(TestActor.java:2598)\r\n\t... 19 more\r\nCaused by: jdk.nashorn.internal.runtime.ParserException: <eval>:5:2 Duplicate Label \"url\"\r\n  url: https://oneapp-STG-py.tigocloud.net/ingresar\r\n  ^\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:272)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:256)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.labelStatement(Parser.java:2549)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1122)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:642)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.labelStatement(Parser.java:2556)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1122)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:642)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.labelStatement(Parser.java:2556)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1122)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:642)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.labelStatement(Parser.java:2556)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1122)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:642)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.labelStatement(Parser.java:2556)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1122)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)\r\n\tat jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)\r\n\t... 24 more\r\n","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.0369062Z","msg":"Executing segment 1 of test logueo-mail/logueo-mail...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.0389097Z","msg":"Evaluating action 1/4 (org.getopentest.selenium.NavigateTo) in segment 1 (Navegar a oneApp)...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":50,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.0999071Z","msg":"ERROR: java.lang.Exception: Failed executing test logueo-mail/logueo-mail, segment 1\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2208)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:3077)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:3113)\r\n\tat org.getopentest.Main.main(Main.java:20)\r\nCaused by: java.lang.RuntimeException: There was an error while executing action no. 1 (org.getopentest.selenium.NavigateTo) in segment 1 of test logueo-mail/logueo-mail.\nThe action definition was:\n{\n  \"action\": \"org.getopentest.selenium.NavigateTo\",\n  \"args\": {\n    \"url\": \"$dataRecord.url.LoginOneAppPROD.url\"\n  },\n  \"description\": \"Navegar a oneApp\"\n}\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2142)\r\n\t... 3 more\r\nCaused by: java.lang.NullPointerException\r\n\tat org.getopentest.base.TestActor.executeActionByDef(TestActor.java:1839)\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2092)\r\n\t... 3 more\r\n","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.6234177Z","msg":"Test session has completed","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":10,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.6254294Z","msg":"TRACE: Firing TEST_COMPLETED event...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":10,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.6294229Z","msg":"TRACE: Firing SESSION_COMPLETED event...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":30,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T18:56:13.63222Z","msg":"Actor 29586 of type ACTOR1 with no tags is waiting to be acquired by a test session...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":10,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T19:00:33.3106674Z","msg":"TRACE: Initializing test session information in the \"announce\" method...","v":0}
{"name":"1730832969","hostname":"DESKTOP-8V10OGQ","pid":32624,"level":10,"actorType":"ACTOR1","actorId":"29586","time":"2024-11-05T19:00:33.3136524Z","msg":"TRACE: Session ID in sync server response was 1730833231; actor session ID was null","v":0}
